name: deploy

on: [push]

env:
  DOTNET_VERSION: 3.1.100
  SOLUTION_FILE: '**/*.sln'
  TEST_PROJECT: '**/**/*Test.csproj'
  TEST_FOLDER: './source/*.Test/'
  COVERAGE_FILE: ./source/coverage.info

jobs:   
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Azure docker login
      run: docker login gaptest.azurecr.io -u ${{ secrets.CONTAINER_REGISTRY_USR }} -p ${{ secrets.CONTAINER_REGISTRY_PWD }}
      
    - name: Build image
      working-directory: ./
      run: docker build -t gaptest.azurecr.io/insuranceapi:latest . -f Dockerfile
      
    - name: Publish image
      working-directory: ./
      run: docker push gaptest.azurecr.io/insuranceapi:latest
      
    - name: Deploy image to azure site via webhooks
      uses: joelwmale/webhook-action@master
      env:
        WEBHOOK_URL: ${{ secrets.AZURE_DEPLOY_WEBHOOK_DEV_URL }}
        data: "Deploying from github actions!"

